### ISSUE TITLE
destination file exists

### ISSUE THREAD

**Issue by kolomenkin** [kolomenkin/limbo#3]
```
DBG> 2019-03-27 10:35:01: Upload file begin
DBG> 2019-03-27 10:35:01: FileStorage: Upload file: фуы5нпрц4унпцюфю.ыцпафуц
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/limbo/server.py", line 163, in cgi_upload
    parser.data_received(chunk)
  File "/usr/local/lib/python3.6/site-packages/streaming_form_data/parser.py", line 57, in data_received
    retval = self._parser.data_received(data)
  File "streaming_form_data/_parser.pyx", line 178, in streaming_form_data._parser._Parser.data_received (streaming_form_data/_parser.c:4159)
  File "streaming_form_data/_parser.pyx", line 236, in streaming_form_data._parser._Parser._parse (streaming_form_data/_parser.c:5043)
  File "streaming_form_data/_parser.pyx", line 147, in streaming_form_data._parser._Parser.set_active_part (streaming_form_data/_parser.c:3512)
  File "streaming_form_data/_parser.pyx", line 92, in streaming_form_data._parser.Part.start (streaming_form_data/_parser.c:2568)
  File "/opt/limbo/server.py", line 138, in start
    self._writer = storage.open_file_writer(self.multipart_filename)
  File "/opt/limbo/lib_file_storage.py", line 123, in open_file_writer
    return AtomicFile(temp_fullname, fullname)
  File "/opt/limbo/lib_file_storage.py", line 48, in __init__
    raise Exception('Destination file already exists')
Exception: Destination file already exists

```

**Comment by kolomenkin** [comment]
I'm pretty sure this issue was fixed 2 years ago. Lets reopen if it will be found again
